export const ShopRouter = "/shop"
export const HomeRouter = "/"
export const RegisterRouter = "/register"
export const AuthRouter = "/auth"
export const HelpRouter = "/help"
export const NewsRouter ="/news"
export const LOCAL_API_URL = "http://localhost:5000/api"